name: assetcraft_ai
description: "AI-powered asset creation tool for developers and designers"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # State Management (Simple Riverpod - no code generation for now)
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.2.7
  
  # Local Database (Isar - Primary storage)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  
  # Cloud Backend (Supabase - FREE tier, better cost control)
  supabase_flutter: ^2.5.6
  
  # Network & HTTP
  dio: ^5.7.0
  http: ^1.2.0
  
  # AI Integration (Gemini)
  google_generative_ai: ^0.4.3
  
  # RevenueCat (Monetization)
  purchases_flutter: ^8.0.0
  
  # Image & Media Handling
  image: ^4.2.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  path: ^1.9.0
  
  # UI Effects (Neumorphism/Glassmorphism)
  flutter_neumorphic_plus: ^3.3.0
  glassmorphism_ui: ^0.3.0
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  share_plus: ^10.0.2
  url_launcher: ^6.3.1
  
  # Development & Debugging
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation (minimal set to avoid conflicts)
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  
  # Assets (create these folders when needed)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
