name: assetcraft_ai
description: "AI-powered asset creation tool for developer"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # State Management (Riverpod with code generation)
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.0  
  
  # Navigation
  go_router: ^14.6.1  
  
  # Local Database (Hive - Primary storage)
  hive: ^2.2.3  
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  
  # Web Storage
  shared_preferences: ^2.3.3
  
  # Cloud Backend (Supabase - FREE tier, better cost control)
  supabase_flutter: ^2.8.3 
  
  # Network & HTTP
  dio: ^5.7.0
  http: ^1.2.2 
  
  # AI Integration (Gemini)
  google_generative_ai: ^0.4.6 
  
  # RevenueCat (Monetization)
  purchases_flutter: ^8.0.4 
  
  # Push Notifications (OneSignal)
  onesignal_flutter: ^5.2.6 
  
  # Google Mobile Ads (Rewarded Ads)
  google_mobile_ads: ^5.3.1
  
  # Image & Media Handling
  image: ^4.2.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  path: ^1.9.0
  
  # UI Effects (Neumorphism/Glassmorphism)
  flutter_neumorphic_plus: ^3.3.0
  glassmorphism_ui: ^0.3.0
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.0 
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  share_plus: ^10.1.2 
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.1.0  # For loading .env files
  
  # Development & Debugging
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation (Riverpod + Hive)
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0 
  hive_generator: ^2.0.1  # Hive code generation

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - .env
    - .env.development
    - .env.staging
    - .env.production
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
